baseURL = 'https://tzz.dev/'
languageCode = 'ja-JP'
defaultContentLanguage = 'ja'
title = "Tzz's Blog"
copyright = "&copy; 2022 tzz.dev"
googleAnalytics = 'G-YTV79RC16K'
[author]
  name = 'tzz'
[params]
  description = "日々の開発メモ、たまにはプライベートのことも。"